version: "3.9"

services:
  api:
    build: .
    container_name: tasks_api
    environment:
      - PORT=${PORT}
      - PYTHON_ENV=${PYTHON_ENV}
      - APP_NAME=${APP_NAME}
      - APP_VERSION=${APP_VERSION}
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
        
    env_file:
      - ./.env.docker
    ports:
      - ${PORT}:${PORT}
    command: bash -c "alembic upgrade head && uvicorn server.main:app --host 0.0.0.0 --port ${PORT} --workers 4"

    restart: on-failure
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
volumes:
  postgres_data:
